language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "Nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "No tests"

script:
  - docker --version # print the version for logging
  - docker-compose build .
  - docker tag reverseproxy ulrichanani/reverseproxy:v1
  - docker tag udagram-api-user ulrichanani/udagram-api-user:v1
  - docker tag udagram-api-feed ulrichanani/udagram-api-feed:v1
  - docker tag udagram-frontend ulrichanani/udagram-frontend:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push ulrichanani/reverseproxy:v1
  - docker push ulrichanani/udagram-api-user:v1
  - docker push ulrichanani/udagram-api-feed:v1
  - docker push ulrichanani/udagram-frontend:v1
