apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend-feed
  name: backend-feed-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: backend-feed
