apiVersion: apps/v1
kind: Deployment
metadata:
  name: reverseproxy
  labels:
    app: reverseproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reverseproxy
  template:
    metadata:
      labels:
        app: reverseproxy
    spec:
      containers:
        - name: reverseproxy
          image: ulrichanani/udagram-reverseproxy:v3
          ports:
            - containerPort: 8080

# Create reverse proxy service
# kubectl expose deployment reverseproxy --type=LoadBalancer --name=reverseproxy-svc